baseURL = "https://troynikov.io"
title = "ANTON"
languageCode = "en-us"

[params]
contentdir = "content"
subscriptionLink = "https://mailchimp.com/your-email-capture-link"

[minify]
  minifyOutput = true
  
  
[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
